---
# tasks file for python
- name: Install pip packages
  ignore_errors: yes
  pip:
      name: "{{item}}"
      state: present
      extra_args: --user
  loop:
      - pelican
      - ghp-import
      - mycli
      - ptpython
      - pipenv
      - pipx
      - yq
  tags:
      - pip
