- name: load vars
  include_vars: apps.yml
- name: Install applications for Ubuntu
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ utilities }}"
  when: ansible_facts['distribution'] == "Ubuntu"
- name: Install applications for Arch-Manjaro
  become: yes
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ utilities }}"
  when: ansible_facts['distribution'] == "Manjaro" or ansible_facts['distribution'] == "ArchLinux"
