- name: Install applications for Ubuntu
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ utilities }}"
    - "{{ apps }}"
  when: "ansible_facts['distribution'] == 'Ubuntu'"
  tags:
    - base-debian
- name: Install applications for Arch-Manjaro
  become: yes
  become_method: sudo
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ utilities }}"
    - "{{ apps }}"
  when: "ansible_facts['distribution'] == 'Archlinux'"
  tags:
    - base-arch
