# ---
 # tasks file for aur
 - name: Install applications for ARCH
   aur:
     use: yay
     aur_only: yes
     name:
       - ttf-font-awesome-4
       - ttf-twemoji-color
       - snapd
       - wireshark-gtk
       - android-studio
       - slack-desktop
       - discord
       - flatpak
       - postman-bin
       - vscodium-bin
       - dropbox
       - aws-cli
       - otf-fira-code-git
       - ttf-jetbrains-mono
       - catt
       - spicetify
       - zeal
       - zoom
   tags:
     - arch-aur
