---
# tasks file for aur
- name: Install from AUR
  aur:
      use: yay
      skip_installed: yes
      aur_only: yes
      name:
      - ttf-font-awesome-4
      - snapd
      - ttf-material-design-icons
      - mailspring
      - wireshark-gtk
      - android-studio
      #- bind
      - slack-desktop
      - discord
      #- tor-browser
  tags:
      - arch-aur
