---
# tasks file for aur
- name: Install from AUR
  aur:
    use: yay
    skip_installed: yes
    aur_only: yes
    name:
      - ttf-font-awesome-4
      - snapd
      - ttf-material-design-icons
      - mailspring
      - wireshark-gtk
      - android-studio
      - slack-desktop
      - discord
      - tor-browser
      - lazygit
      - flatpak
      - postman-bin
      - spotify
      - visual-studio-code-bin
      - dropbox
      - wps-office
      - notion-app
  tags:
    - arch-aur
