--- # Main playbook
- hosts: localhost 
  gather_facts: yes
  connection: local
  roles:
      #- base
      #- python
      #- snaps
    - shell
  tasks:
      #- include_role:
      #  name : aur
      #when: "ansible_facts['distribution'] == 'Archlinux'"
  #  - gaming
  #  - flatpaks
    - include_role:
        name: windows 
      when: "ansible_facts['os_family'] == 'wndows'"
