--- # Main playbook
- hosts: localhost
  gather_facts: yes
  connection: local
  roles:
    - base
    - python
    - snaps
    - shell
    - flatpaks
  tasks:
    - include_role:
        name : base
      when: "ansible_facts['distribution'] == 'Archlinux'"
    - include_role:
        name: windows 
      when: "ansible_facts['os_family'] == 'windows'"
