---
# tasks file for shell
- name: Tasks for shell setup
  block:
    - name: Install Vim Bundle
      git:
          repo: https://github.com/VundleVim/Vundle.vim.git
          dest: /home/$USER/.vim/bundle/Vundle.vim
    - name: setup p10k
      git:
          repo: https://github.com/romkatv/powerlevel10k.git
          dest: $HOME/.oh-my-zsh/custom/themes/powerlevel10k
          depth: 1
    - name: Create vim folder
      file:
           path: /home/$USER/.config/nvim
           state: directory
    - name: Copy nvim files
      copy:
          src: /home/$USER/dotfiles/nvim/init.vim
          dest: /home/$USER/.config/nvim/init.vim
    - name: Copy zsh files
      copy:
          src: /home/$USER/dotfiles/zsh/.zshrc
          dest: /home/$USER/.zshrc
    - name: Copy p10k files
      copy:
          src: /home/$USER/dotfiles/zsh/.p10k.zsh
          dest: /home/$USER/.p10k.zsh
    - name: Copy tmux files
      copy:
          src: /home/$USER/dotfiles/tmux/.tmux.conf
          dest: /home/$USER/.tmux.conf
  tags:
  - shell
